FROM prefecthq/prefect:latest

WORKDIR /app

#Installing Files (1. relativer Pfad bei ausführen docker build /// 2. Absoluter Pfad INNERHALB DockerFile/Container)
COPY test_run_flow_on_dockerimage.py /app/test_run_flow_on_dockerimage.py